### ISSUE TITLE
Missing native library dependency for dbus service

### ISSUE THREAD

**Issue by MichaelBitard** [jnr/jffi#86] opened 2020-08-08 16:34 UTC
I'm using this through signal-cli, I initially opened an issue there (AsamK/signal-cli#321) and the maintainer rightfully redirected me here.

I'm having an error message with one architecture: aarch64 (rpi4)

`Missing native library dependency for dbus service: could not load FFI provider jnr.ffi.provider.jffi.Provider`

Is this something path related that I can fix myself or a know issue?

**Comment by headius** [comment] 2020-08-12 16:48
We definitely do ship support for Linux aarch64, so perhaps signal-cli is depending on an older version of the JNR projects?

**Comment by headius** [comment] 2020-08-12 16:52
If you could provide the full error output, that would also be helpful.

I'm not sure if this is the version of dbus-java that's being used, but it appears to be using the most recent jnr-unixsocket. It may not be the version that's getting used in your case, though.

https://github.com/hypfvieh/dbus-java/blob/master/pom.xml#L201-L205

**Comment by MichaelBitard** [comment] 2020-08-16 11:43
The aarch64.so file is present in the -native.jar that is shipped with signal-cli.
I opened multiple issues because I did not know where this problem could come from. I had some answers here: https://github.com/jnr/jnr-ffi/issues/206.
Should I close this issue in favor of https://github.com/jnr/jnr-ffi/issues/206 ?

**Comment by headius** [comment] 2020-12-02 19:28
Sorry for the delay in responding here. If you can show me how to reproduce this maybe it is a simple fix. I have access to some limited aarch64 environments.

**Comment by headius** [comment] 2020-12-02 21:15
Based on jnr/jnr-ffi#206 it seems like this may simply have been a build issue in signal-cli that omitted the required jffi native jar. I am optimistically closing this as invalid, but if it turns out we are doing something wrong please let us know.

**Closed by headius** 2020-12-02 21:15 UTC
